export const Constructor = Symbol('Constructor')
export const Methods = Symbol('Methods')
export const Name = Symbol('Name')
export const ArtifactSymbol = Symbol('ArtifactSymbol')
export const Type = Symbol('Type')
export const Address = Symbol('Address')
export const AbiSymbol = Symbol('Abi')
export const Bytecode = Symbol('Bytecode')
