name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: ['10.x', '12.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn test
