name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [16, 14, 12]
        os: [ubuntu-latest]
        lts: [true]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.lts }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn build
    - run: yarn cover
