name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node: [16, 14]
        os: [ubuntu-latest]
        lts: [true]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.lts }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.1.9
        run_install: false
    - run: pnpm i
    - run: pnpm run lint
    - run: pnpm run build
    - run: pnpm run cover
